routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'ProductController@main')->name('home');
Auth::routes();

Route::resource('products', 'ProductController')->names([
    'create' => 'products.add'
])->middleware('auth');

Route::get('auth/facebook','Auth\FacebookController@redirectToFacebook')->name('auth-facebook');
Route::get('auth/facebook/callback', 'Auth\FacebookController@handleFacebookCallback');

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Entity\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class ProductController extends Controller
{
    public function main()
    {
        return view('main', ['title' => 'Marketplace']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        return view('products.index', ['products' => $products, 'title' => 'List of products']);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.add', ['title' => 'Create product']);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Product::create(['name' => $request->name, 'price' => $request->price, 'user_id' => $request->user()->id]);
        return redirect()->route('products.index');
    }

    /**
     * Display the specified resource.
     *
     * @param Product $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('products.show', ['product' => $product, 'title' => 'Information about product']);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Product $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        if (Gate::allows('update', $product)) {
            return view('products.edit', ['product' => $product, 'title' => 'Edit product']);
        }
        return redirect()->route('home');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param Product $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        if (Gate::denies('update', $product)) {
            return redirect()->route('home');
        }
        $product->name = $request->name;
        $product->price = $request->price;
        $product->save();
        return redirect()->route('products.show', ['product' => $product->id]);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Product $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        if (Gate::denies('delete', $product)) {
            return redirect()->route('home');
        }
        $product->delete();
        return redirect()->route('products.index');
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title')</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                Marketplace
            </a>
{{--            @can('create',\App\Entity\Product::class)--}}
                <a class="navbar-brand" href="{{ route('products.add') }}">
                    Add
                </a>
{{--            @endcan--}}
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                      style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        @yield('content')
    </main>
</div>
</body>
</html>

resources/views/main.blade.php
@extends('layouts.app')

@section('title',$title)

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <p class="text-center h1">Marketplace</p>
            </div>
        </div>
    </div>
@endsection

resources/views/products/add.blade.php
@extends('layouts.app')

@section('title',$title)

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-5">
            <form role="form" method="post" action="{{route('products.store')}}">
                {{csrf_field()}}
                <div class="form-group">
                    <label for="nameProduct">Name product</label>
                    <input type="text" class="form-control" name="name" id="nameProduct"
                           value="" placeholder="Enter name">
                </div>
                <div class="form-group">
                    <label for="short_name">Price</label>
                    <input type="text" class="form-control" name="price" id="price"
                           value="" placeholder="Enter price">
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>
@endsection

resources/views/products/edit-delete-buttons.blade.php
<td class="text-center">
    <a href="{{route('products.edit',['id'=>$productId])}}" class="btn btn-primary btn-sm"
       role="button">Edit</a>
</td>
<td class="text-center">
    <form method="post" action="{{route('products.destroy',['id'=>$productId])}}">
        @method('delete')
        @csrf
        <input type="submit" class="btn-sm btn btn-primary" value="Delete">
    </form>
</td>

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('title',$title)

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-5">
            <form role="form" method="post" action="{{route('products.update',['product'=>$product])}}">
                @method('put')
                @csrf
                <div class="form-group">
                    <label for="nameProduct">Name product</label>
                    <input type="text" class="form-control" name="name" id="nameProduct"
                           value="{{$product->name}}" placeholder="Enter name">
                </div>
                <div class="form-group">
                    <label for="short_name">Price</label>
                    <input type="text" class="form-control" name="price" id="price"
                           value="{{$product->price}}" placeholder="Enter price">
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>
@endsection

resources/views/products/index.blade.php
@extends('layouts.app')

@section('title',$title)

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Price</th>
                        <th scope="col">Edit</th>
                        <th scope="col">Delete</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($products as $product)
                        <tr>
                            <th scope="row">{{$product->id}}</th>
                            <td><a href="{{route('products.show',['product'=>$product->id])}}">
                                    {{$product->name}}</a>
                            </td>
                            <td>{{$product->price}}</td>
                            @can('show-edit-delete-buttons',$product)
                                @component('products.edit-delete-buttons',['productId' => $product->id])
                                @endcomponent
                            @endcan
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/products/show.blade.php
@extends('layouts.app')

@section('title',$title)

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Price</th>
                        @can('show-edit-delete-buttons',$product)
                            <th scope="col">Edit</th>
                            <th scope="col">Delete</th>
                        @endcan
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <th scope="row">{{$product->id}}</th>
                        <td>{{$product->name}}</td>
                        <td>{{$product->price}}</td>
                        @can('show-edit-delete-buttons',$product)
                            @component('products.edit-delete-buttons',['productId' => $product->id])
                            @endcomponent
                        @endcan
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection